model: STARGAN_V2
sty_dim: 64
w_hpf: 1

loss: regression_loss
metrics: [inter_ocular_error]
epoch: 300

keypoint_regressor:
    type: IntermediateKeypointPredictor
    args:
        input_channel: 512
        num_annotated_points: 5
        num_intermediate_points: 50
        softargmax_mul: 100

optimizer:
    type: Adam
    args:
        lr: 0.0005
        weight_decay: 0.0005
        amsgrad: true

lr_scheduler:
    type: MultiStepLR
    args:
        milestones: [50, 100, 150, 200, 250]
        gamma: 0.3

data:
    dataset: AFLW
    task: None # for which task data is served (Munit, None, ...)
    root: /home/nas1_userE/ULD_dataset/aflw/aflw_release-2
    use_keypoints: True # return keypoints in dataloader, True or False
    batch_size: 32
    transform: 
        CenterCrop: [256, 256]  # [h, w] or scalar
        Resize: 256 # scalar

