model: TUNIT
img_size: 256
sty_dim: 128
output_k: 10
dims: 2048

keypoint_regressor:
    type: IntermediateKeypointPredictor
    args:
        input_channel: 
        num_annotated_points: 5
        num_intermediate_points: 50
        softargmax_mul: 100
