model: TUNIT
img_size: 128 
sty_dim: 128
output_k: 10
dims: 2048
loss: regression_loss
metrics: [inter_ocular_error]
epoch: 300

keypoint_regressor:
    type: IntermediateKeypointPredictor
    args:
        input_channel: 512
        num_annotated_points: 68
        num_intermediate_points: 50
        softargmax_mul: 100

optimizer:
    type: Adam
    args:
        lr: 0.0005
        weight_decay: 0.0005
        amsgrad: true

lr_scheduler:
    type: MultiStepLR
    args:
        milestones: [100, 250]
        gamma: 0.1

data:
    dataset: ThreeHundredW
    task: None # for which task data is served (Munit, None, ...)
    root: /home/nas1_userE/ULD_dataset/300w/300w
    use_keypoints: True # return keypoints in dataloader, True or False
    batch_size: 32
    imwidth: 256
    crop: 0
