data:
    dataset: CelebAAligned4MAFLVal
    objective: Munit
    root: '/home/junhahyung/dataset/data/celeba'
    batch_size: 32
    default_h: 218 # default height
    default_w: 178 # default width
    use_hq_ims: True
    val_split: celeba
    val_size: 2000
    transform: 
        CenterCrop: [256, 256]  # (h, w) or scalar
        Resize: 256 # scalar

